"use client";

import { Raleway } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { RecoilRoot } from "recoil";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const raleway = Raleway({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_API_KEY}&libraries=places&callback=initMap`}
          strategy="beforeInteractive"
        /> */}
        <Script src="https://checkout.razorpay.com/v1/checkout.js"></Script>
      </head>
      <body className={raleway.className}>
        <RecoilRoot>
          <Toaster />
          <Navbar />
          {children}
          <Footer />
        </RecoilRoot>
      </body>
    </html>
  );
}
